name: HRC-CEMS
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python
  - pandas=2.0.3
  - numpy=1.24.3
  - scipy=1.11.1
  - openpyxl=3.1.2
  - google-auth=2.17.3
  - google-auth-oauthlib=1.0.0
  - google-auth-httplib2=0.1.0
  - beautifulsoup4=4.12.2
  - requests=2.31.0
  - flask=2.3.3
  - transformers=4.30.2
  - pytorch  # Sin versi√≥n
  - matplotlib=3.7.2
  - python-dotenv=1.0.0
  - pip
  - pip:
    - gspread==5.10.0